"""add transcription tracking fields

Revision ID: 010e0adbdcbe
Revises: 5f05af4fc65c
Create Date: 2026-08-03 12:20:43.334010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '010e0adbdcbe'
down_revision: Union[str, Sequence[str], None] = '5f05af4fc65c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recordings', sa.Column('transcription_error', sa.Text(), nullable=True))
    op.add_column('recordings', sa.Column('transcription_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('recordings', sa.Column('transcription_completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recordings', 'transcription_completed_at')
    op.drop_column('recordings', 'transcription_started_at')
    op.drop_column('recordings', 'transcription_error')
    # ### end Alembic commands ###
