"""add reviewed notes

Revision ID: dbfb312ffa96
Revises: ec92c9548c82
Create Date: 2026-09-21 10:31:29.245978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbfb312ffa96'
down_revision: Union[str, Sequence[str], None] = 'ec92c9548c82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviewed_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('generated_note_id', sa.Uuid(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('decisions_json', sa.Text(), nullable=False),
    sa.Column('action_items_json', sa.Text(), nullable=False),
    sa.Column('key_points_json', sa.Text(), nullable=False),
    sa.Column('follow_up_questions_json', sa.Text(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generated_note_id'], ['generated_notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviewed_notes_generated_note_id'), 'reviewed_notes', ['generated_note_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviewed_notes_generated_note_id'), table_name='reviewed_notes')
    op.drop_table('reviewed_notes')
    # ### end Alembic commands ###
