"""add generated notes

Revision ID: ec92c9548c82
Revises: 010e0adbdcbe
Create Date: 2026-08-13 12:09:57.833056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec92c9548c82'
down_revision: Union[str, Sequence[str], None] = '010e0adbdcbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transcript_id', sa.Uuid(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('decisions_json', sa.Text(), nullable=False),
    sa.Column('action_items_json', sa.Text(), nullable=False),
    sa.Column('key_points_json', sa.Text(), nullable=False),
    sa.Column('follow_up_questions_json', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_notes_transcript_id'), 'generated_notes', ['transcript_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_notes_transcript_id'), table_name='generated_notes')
    op.drop_table('generated_notes')
    # ### end Alembic commands ###
